# Generated by Django 4.2.4 on 2023-09-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='link',
        ),
    ]
